# Week 7 {.unnumbered}

## Doing Data Science {.unnumbered}

<p>

This week you will learn additional techniques that are integral to Data Science.

::: {.slide-deck}
**Unit 2 - Deck 17: Doing data science**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d17-doing-data-science/u2-d17-doing-data-science.html#1)
:::

::: {.video}
[Video](https://youtu.be/b9lSW0kyqBg)
:::

::: {.reading}
R4DS :: [Chp 7 - Exploratory data analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html)
:::
:::

## Exercise: Legos {.unnumbered}

<p>

Download and open the **Legos** R-markdown file from Blackboard.
Open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.

## Lab: LaQuinta - Part II {.unnumbered}

<p>

Download and open the **LaQuinta Part II** R-markdown file from Blackboard.
This file is contained within a zip file.
Open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.
