# Week 4 {.unnumbered}

## More Data Wrangling {.unnumbered}

<p>

This week you will obtain additional practice with data wrangling.
Complete the tutorials, and then complete the **College Majors** activity.

## Tutorials {.unnumbered}

::: {.tutorial}
**Tutorial 1: Airbnb listings in Edinburgh**

The goal of this tutorial is not to conduct a thorough analysis of Airbnb listings in Edinburgh, but instead to give you a chance to practice your data visualisation and interpretation skills.

[[Tutorial]](https://minecr.shinyapps.io/dsbox-01-edibnb/) [[Source]](https://github.com/rstudio-education/dsbox/tree/master/inst/tutorials/01-basics)
:::

::: {.tutorial}
**Tutorial 2: Road Traffic Accidents**

-   Continue practising data visualization skills with ggplot2.
-   Filter data for certain attributes with `filter()`.
-   Create new variables based on existing variables in the data with `mutate()`.

[[Tutorial]](https://minecr.shinyapps.io/dsbox-02-accidents/) [[Source]](https://github.com/rstudio-education/dsbox/tree/master/inst/tutorials/02-accidents)
:::

## Lab: College Majors {.unnumbered}

<p>

Download the zip folder containing the **College Majors** markdown document and supporting files, and open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.
