# Week 3 {.unnumbered}

## Wrangling and Tidying Data {.unnumbered}

<p>

The topics of this week are:

-   Tidy data

-   Data wrangling

-   Working with single data frames

-   Working with multiple data frames

-   Tidying data

<p>

Please complete the following tasks.
As you watch the videos, you can practice the commands by uploading the corresponding data sets.
The data sets associated with these lessons are available in the Week 3 Data Files zip file (in Blackboard).

<p>

Also, you can open up the **Hotels & Data Wrangling** markdown file (described below) and work on the assignment as you watch the videos, rather than waiting until after you watch all the videos.
This file is located in Blackboard.

::: {.slide-deck}
**Unit 2 - Deck 5: Tidy data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d05-tidy-data/u2-d05-tidy-data.html#1)
:::

::: {.video}
[Video](https://youtu.be/Ux85eR3h9hw)
:::

::: {.reading}
JSS :: [Tidy data](https://www.jstatsoft.org/article/view/v059i10)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 6: Grammar of data wrangling**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d06-grammar-wrangle/u2-d06-grammar-wrangle.html#1)
:::

::: {.video}
[Video](https://youtu.be/ZCaYBES_VEk)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 7: Working with a single data frame**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d07-single-df/u2-d07-single-df.html#1)
:::

::: {.video}
[Video](https://youtu.be/0229Uq2hkJo)
:::

::: {.reading}
R4DS :: [Chp 5 - Data transformation](https://r4ds.had.co.nz/transform.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 8: Working with multiple data frames**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d08-multi-df/u2-d08-multi-df.html#1)
:::

::: {.video}
[Video](https://youtu.be/VdV5ABsaf5Y)
:::

::: {.reading}
R4DS :: [Chp 13 - Relational data](https://r4ds.had.co.nz/relational-data.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 9: Tidying data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d09-tidying/u2-d09-tidying.html#1)
:::

::: {.video}
[Video](https://youtu.be/x3KM5uxaFdI)
:::

::: {.reading}
R4DS :: [Chp 12 - Tidy data](https://r4ds.had.co.nz/tidy-data.html)
:::
:::

## Exercise: Hotel Bookings - Data Wrangling {.unnumbered}

<p>

Download the **Hotels & Data Wrangling** R-markdown file from Blackboard and open it in R-Studio.

**Instructions:**

1.  Set yourself as the "author" of the document.

2.  Solve the problems in Exercises 1 - 8.

3.  After you make the changes to the markdown document, save your work.
    Make sure that the document has no errors and can be "knit" successfully.

4.  Save and rename the file as "yourname_hotels.Rmd".

5.  Upload your revised markdown document to the assignment in Blackboard.

## Lab: Nobel Laurates {.unnumbered}

<p>

Download the zip folder containing the **Nobel Lab** markdown document and supporting files, and open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.
