# Week 6 {.unnumbered}

## Communicating Data Science Results Effectively {.unnumbered}

<p>

This assignment focuses on best practices in data visualization.

::: {.slide-deck}
**Unit 2 - Deck 14: Tips for effective data visualization**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d14-effective-dataviz/u2-d14-effective-dataviz.html#1)
:::

::: {.video}
[Video](https://youtu.be/ZrifrBvFWgg)
:::

::: {.reading}
IMS :: [Chp 6 - Applications: Explore](https://openintro-ims.netlify.app/explore-applications.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 15: Scientific studies and confounding**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d15-studies-confounding/u2-d15-studies-confounding.html#1)
:::

::: {.video}
[Video](https://youtu.be/WnMzTBrZDcc)
:::

::: {.reading}
IMS :: [Chp 2 - Study design](https://openintro-ims.netlify.app/data-design.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 16: Simpson's paradox**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d16-simpsons-paradox/u2-d16-simpsons-paradox.html#1)
:::

::: {.video}
[Video](https://youtu.be/sdas62v0iJU)
:::
:::

## Lab: Simpsons Paradox {.unnumbered}

<p>

Download and open the **Simpsons Paradox** R-markdown file from Blackboard.
This file is contained within a zip file.
Open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.

## Exercise: Brexit & Telling Stories {.unnumbered}

<p>

Download and open the **Brexit** R-markdown file from Blackboard.
This file is contained within a zip file.
Open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.

## Lab: Sad Plots {.unnumbered}

<p>

Download and open the **Sad Plots** R-markdown file from Blackboard.
This file is contained within a zip file.
Open it in R-Studio.

**Instructions:**

1.  Knit the markdown document to make sure the file compiles successfully.
2.  Edit the markdown document as instructed.
3.  Rename and upload the completed markdown file to the assignment in Blackboard.
